In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
plt.rc("font", size=16)

from sklearn.preprocessing import StandardScaler 
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.model_selection import GridSearchCV, cross_val_score, RepeatedStratifiedKFold, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, roc_auc_score, precision_score, recall_score, precision_recall_curve
from sklearn.metrics import f1_score

df = pd.read_csv("./data/clean_one_hot_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

scaler = StandardScaler()
scaler.fit_transform(df)

y = df['attrition']
X = df.drop(columns=['attrition'])

w = {0:15, 1:85}

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
logreg = LogisticRegression(max_iter=5000, class_weight=w)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# con_matrix = confusion_matrix(y_test, y_pred).ravel()

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.7554347826086957
Confusion Matrix: 
[[244  76]
 [ 14  34]]
Area Under Curve: 0.7354166666666667
Recall score: 0.7083333333333334


/home/tnbakke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [26]:
df = pd.read_csv("./data/clean_one_hot_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

scaler = StandardScaler()
scaler.fit_transform(df)

y = df['attrition']
X = df.drop(columns=['attrition'])

w = {0:10, 1:90}

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
logreg = LogisticRegression(max_iter=5000, class_weight=w)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# con_matrix = confusion_matrix(y_test, y_pred).ravel()

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.6494565217391305
Confusion Matrix: 
[[200 120]
 [  9  39]]
Area Under Curve: 0.71875
Recall score: 0.8125


/home/tnbakke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [28]:
df = pd.read_csv("./data/clean_one_hot_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

scaler = StandardScaler()
scaler.fit_transform(df)

y = df['attrition']
X = df.drop(columns=['attrition'])

w = {0:5, 1:95}

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
logreg = LogisticRegression(max_iter=5000, class_weight=w)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# con_matrix = confusion_matrix(y_test, y_pred).ravel()

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.5
Confusion Matrix: 
[[144 176]
 [  8  40]]
Area Under Curve: 0.6416666666666666
Recall score: 0.8333333333333334


In [29]:
# from documentation: tn, fp, fn, tp

In [30]:
lasso_coeffs = ['daily_rate', 'monthly_income', 'job_satisfaction', 
                'business_travel', 'years_at_company', 'age']

In [31]:
df = pd.read_csv("./data/clean_one_hot_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

y = df['attrition']
X = df[lasso_coeffs]

w = {0:10, 1:90}

from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
scaler.fit_transform(df)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
logreg = LogisticRegression(max_iter=5000, class_weight=w)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# con_matrix = confusion_matrix(y_test, y_pred).ravel()

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.38315217391304346
Confusion Matrix: 
[[ 98 222]
 [  5  43]]
Area Under Curve: 0.6010416666666667
Recall score: 0.8958333333333334


In [32]:
df = pd.read_csv("./data/clean_one_hot_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

y = df['attrition']
X = df[lasso_coeffs]

w = {0:5, 1:95}

from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
scaler.fit_transform(df)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
logreg = LogisticRegression(max_iter=5000, class_weight=w)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

# con_matrix = confusion_matrix(y_test, y_pred).ravel()

print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.1983695652173913
Confusion Matrix: 
[[ 27 293]
 [  2  46]]
Area Under Curve: 0.5213541666666667
Recall score: 0.9583333333333334
