In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import roc_curve, precision_recall_curve, auc, make_scorer, recall_score, accuracy_score, precision_score, confusion_matrix

In [2]:
import matplotlib.pyplot as plt
plt.style.use("ggplot")

df = pd.read_csv("../data/clean_one_hot_emp_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

In [3]:
df.head()

age  attrition  business_travel  daily_rate  distance_from_home  education  \
0   41          1                1        1102                   1          2   
1   49          0                2         279                   8          1   
2   37          1                1        1373                   2          2   
3   33          0                2        1392                   3          4   
4   27          0                1         591                   2          1   

   environment_satisfaction  gender  hourly_rate  job_involvement  ...  \
0                         2       0           94                3  ...   
1                         3       1           61                2  ...   
2                         4       1           92                2  ...   
3                         4       0           56                3  ...   
4                         1       1           40                3  ...   

   job_role_sales representative  department_research & development  \
0                              0                                  0   
1                              0                                  1   
2                              0                                  1   
3                              0                                  1   
4                              0                                  1   

   department_sales  education_field_life sciences  education_field_marketing  \
0                 1                              1                          0   
1                 0                              1                          0   
2                 0                              0                          0   
3                 0                              1                          0   
4                 0                              0                          0   

   education_field_medical  education_field_other  \
0                        0                      0   
1                        0                      0   
2                        0                      1   
3                        0                      0   
4                        1                      0   

   education_field_technical degree  marital_status_married  \
0                                 0                       0   
1                                 0                       1   
2                                 0                       0   
3                                 0                       1   
4                                 0                       1   

   marital_status_single  
0                      1  
1                      0  
2                      1  
3                      0  
4                      0  

[5 rows x 44 columns]

In [4]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
gb = GradientBoostingClassifier(random_state = 42)

In [6]:
y = df.attrition
X = df.drop('attrition',axis=1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [8]:
gb.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [9]:
y_pred = gb.predict(X_test)

In [10]:
cm = confusion_matrix(y_test, y_pred)
print('The confusion Matrix : \n',cm)

The confusion Matrix : 
 [[311   9]
 [ 33  15]]


In [11]:
cm.ravel()

array([311,   9,  33,  15])

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, roc_auc_score, precision_score, recall_score, precision_recall_curve


In [13]:
print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.8858695652173914
Confusion Matrix: 
[[311   9]
 [ 33  15]]
Area Under Curve: 0.6421875
Recall score: 0.3125


In [14]:
df.describe()

age    attrition  business_travel   daily_rate  \
count  1470.000000  1470.000000      1470.000000  1470.000000   
mean     36.923810     0.161224         1.086395   802.485714   
std       9.135373     0.367863         0.532170   403.509100   
min      18.000000     0.000000         0.000000   102.000000   
25%      30.000000     0.000000         1.000000   465.000000   
50%      36.000000     0.000000         1.000000   802.000000   
75%      43.000000     0.000000         1.000000  1157.000000   
max      60.000000     1.000000         2.000000  1499.000000   

       distance_from_home    education  environment_satisfaction       gender  \
count         1470.000000  1470.000000               1470.000000  1470.000000   
mean             9.192517     2.912925                  2.721769     0.600000   
std              8.106864     1.024165                  1.093082     0.490065   
min              1.000000     1.000000                  1.000000     0.000000   
25%              2.000000     2.000000                  2.000000     0.000000   
50%              7.000000     3.000000                  3.000000     1.000000   
75%             14.000000     4.000000                  4.000000     1.000000   
max             29.000000     5.000000                  4.000000     1.000000   

       hourly_rate  job_involvement  ...  job_role_sales representative  \
count  1470.000000      1470.000000  ...                    1470.000000   
mean     65.891156         2.729932  ...                       0.056463   
std      20.329428         0.711561  ...                       0.230891   
min      30.000000         1.000000  ...                       0.000000   
25%      48.000000         2.000000  ...                       0.000000   
50%      66.000000         3.000000  ...                       0.000000   
75%      83.750000         3.000000  ...                       0.000000   
max     100.000000         4.000000  ...                       1.000000   

       department_research & development  department_sales  \
count                        1470.000000       1470.000000   
mean                            0.653741          0.303401   
std                             0.475939          0.459884   
min                             0.000000          0.000000   
25%                             0.000000          0.000000   
50%                             1.000000          0.000000   
75%                             1.000000          1.000000   
max                             1.000000          1.000000   

       education_field_life sciences  education_field_marketing  \
count                    1470.000000                1470.000000   
mean                        0.412245                   0.108163   
std                         0.492406                   0.310692   
min                         0.000000                   0.000000   
25%                         0.000000                   0.000000   
50%                         0.000000                   0.000000   
75%                         1.000000                   0.000000   
max                         1.000000                   1.000000   

       education_field_medical  education_field_other  \
count              1470.000000            1470.000000   
mean                  0.315646               0.055782   
std                   0.464931               0.229579   
min                   0.000000               0.000000   
25%                   0.000000               0.000000   
50%                   0.000000               0.000000   
75%                   1.000000               0.000000   
max                   1.000000               1.000000   

       education_field_technical degree  marital_status_married  \
count                       1470.000000             1470.000000   
mean                           0.089796                0.457823   
std                            0.285986                0.498387   
min                            0.000000                0.000000   
25%        

In [7]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import roc_curve, precision_recall_curve, auc, make_scorer, recall_score, accuracy_score, precision_score, confusion_matrix

import matplotlib.pyplot as plt
plt.style.use("ggplot")

df = pd.read_csv("../data/clean_one_hot_emp_data.csv")
df.drop(df.columns[0], axis=1,inplace=True)

y = df.attrition
X = df.drop('attrition',axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

num_estimators = [100, 200,500,1000]
learn_rates = [0.01, 0.05, 0.10]
max_depths = [1, 2, 3]
min_samples_leaf = [1, 5,10]
min_samples_split = [2, 5,10]

param_grid = {'n_estimators': num_estimators,
              'learning_rate': learn_rates,
              'max_depth': max_depths,
              'min_samples_leaf': min_samples_leaf,
              'min_samples_split': min_samples_split}

gb = GradientBoostingClassifier(random_state=42)

gb_random_search = RandomizedSearchCV(gb, param_distributions = param_grid, random_state=42)

gb_random_search.fit(X_train, y_train)

gb_random_search.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_depth': 1,
 'learning_rate': 0.1}

In [8]:
gb_optimal = GradientBoostingClassifier(n_estimators= 1000, min_samples_split = 2, min_samples_leaf = 1,
                                         max_depth = 1, learning_rate = 0.1)

In [9]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [10]:
gb_optimal.fit(X_train, y_train)

GradientBoostingClassifier(max_depth=1, n_estimators=1000)

In [11]:
y_pred = gb_optimal.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, roc_auc_score, precision_score, recall_score, precision_recall_curve

cm = confusion_matrix(y_test, y_pred)
print('The confusion Matrix : \n',cm)

The confusion Matrix : 
 [[306  14]
 [ 30  18]]


In [13]:
print(f'Accuracy Score: {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
print(f'Area Under Curve: {roc_auc_score(y_test, y_pred)}')
print(f'Recall score: {recall_score(y_test,y_pred)}')

Accuracy Score: 0.8804347826086957
Confusion Matrix: 
[[306  14]
 [ 30  18]]
Area Under Curve: 0.665625
Recall score: 0.375


In [14]:
y_test

1041    0
184     0
1222    1
67      0
220     0
       ..
571     0
1163    0
243     0
1411    0
1370    0
Name: attrition, Length: 368, dtype: int64

In [15]:
y_test.describe()

count    368.000000
mean       0.130435
std        0.337240
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: attrition, dtype: float64

In [22]:
y_test = pd.Series(y_test)

In [24]:
y_test.value_counts()

0    320
1     48
Name: attrition, dtype: int64

In [25]:
df.head()

age  attrition  business_travel  daily_rate  distance_from_home  education  \
0   41          1                1        1102                   1          2   
1   49          0                2         279                   8          1   
2   37          1                1        1373                   2          2   
3   33          0                2        1392                   3          4   
4   27          0                1         591                   2          1   

   environment_satisfaction  gender  hourly_rate  job_involvement  ...  \
0                         2       0           94                3  ...   
1                         3       1           61                2  ...   
2                         4       1           92                2  ...   
3                         4       0           56                3  ...   
4                         1       1           40                3  ...   

   job_role_sales representative  department_research & development  \
0                              0                                  0   
1                              0                                  1   
2                              0                                  1   
3                              0                                  1   
4                              0                                  1   

   department_sales  education_field_life sciences  education_field_marketing  \
0                 1                              1                          0   
1                 0                              1                          0   
2                 0                              0                          0   
3                 0                              1                          0   
4                 0                              0                          0   

   education_field_medical  education_field_other  \
0                        0                      0   
1                        0                      0   
2                        0                      1   
3                        0                      0   
4                        1                      0   

   education_field_technical degree  marital_status_married  \
0                                 0                       0   
1                                 0                       1   
2                                 0                       0   
3                                 0                       1   
4                                 0                       1   

   marital_status_single  
0                      1  
1                      0  
2                      1  
3                      0  
4                      0  

[5 rows x 44 columns]

In [26]:
df.attrition.value_counts()

0    1233
1     237
Name: attrition, dtype: int64

In [27]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [33]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0,1]).ravel()

In [34]:
tn

306

In [35]:
fp

14

In [36]:
fn

30

In [37]:
tp

18

In [38]:
print(tp,fp,fn,tn)

18 14 30 306
